version: '3.8'

services:
  app:
    image: imprazz/getting-started2:swarmmode  # Menambahkan image baru
    command: sh -c "sleep 20 && yarn install && yarn run dev"
    ports:
      - 80:3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=todos
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos
    deploy:
      replicas: 1
    volumes:
      - app_todo-mysql-data:/var/lib/mysql

volumes:
  app_todo-mysql-data:
