# version: '3'

# services:
#   app:
#     image: node:18-alpine
#     command: sh -c "sleep 20 && yarn install && yarn run dev"
#     ports:
#       - 80:3000
#     working_dir: /app
#     volumes:
#       - app_todo-app-data:/app
#     environment:
#       - MYSQL_HOST=mysql
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=secret
#       - MYSQL_DB=todos
#     depends_on:
#       - mysql
#     deploy:
#       replicas: 3
#       restart_policy:
#         condition: on-failure
#       update_config:
#         delay: 20s

#   mysql:
#     image: mysql:8.0
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_ROOT_PASSWORD=secret
#       - MYSQL_DATABASE=todos
#     deploy:
#       replicas: 1
#     volumes:
#       - app_todo-mysql-data:/var/lib/mysql

# volumes:
#   app_todo-app-data:
#     driver_opts:
#       type: nfs
#       o: addr=10.184.0.3,rw
#       device: ":/home/imprazz07/getting-started2/app"
#   app_todo-mysql-data:
  


# version: '3'

# services:
#   app:
#     image: node:18-alpine
#     command: sh -c "sleep 20 && yarn install && yarn run dev"
#     ports:
#       - 80:80
#     working_dir: /app
#     volumes:
#       - ./:/app
#     environment:
#       - MYSQL_HOST=mysql
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=secret
#       - MYSQL_DB=todos
#     depends_on:
#       - mysql
#     deploy:
#       replicas: 3
#       restart_policy:
#         condition: on-failure
#       update_config:
#         delay: 20s

#   mysql:
#     image: mysql:8.0
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_ROOT_PASSWORD=secret
#       - MYSQL_DATABASE=todos
#     deploy:
#       replicas: 1
#       restart_policy:
#         condition: on-failure
#     volumes:
#       - app_todo-mysql-data:/var/lib/mysql
  
#   grafana:
#     image: grafana:latest
#     ports:
#       - "3000:3000"
#     depends_on:
#       - redis

#   adapter:
#     image: "redislabs/prometheus-redistimeseries-adapter:master"
#     command: ["-redis-address", "redis:6379", "-web.listen-address", "0.0.0.0:9201"]
#     depends_on:
#       - redis

#   redis:
#     image: "redislabs/redistimeseries:edge"
#     ports:
#       - "6379:6379"
#     deploy:
#       replicas: 1
#       restart_policy:
#         condition: on-failure

#   prometheus:
#     image: "prom/prometheus:v2.41.0"
#     command: ["--config.file=/prometheus.yml"]
#     volumes:
#       - ./prometheus.yaml:/prometheus.yml
#     ports:
#       - 9090:9090

# volumes:
#   app_todo-mysql-data:

version: '3'

services:
  app:
    image: node:18-alpine
    command: sh -c "sleep 20 && yarn install && yarn run dev"
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=todos
    depends_on:
      - mysql
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        delay: 20s
    networks:
      - app_net

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - app_todo-mysql-data:/var/lib/mysql
    networks:
      - app_net

  grafana:
    image: grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app_net

  adapter:
    image: "redislabs/prometheus-redistimeseries-adapter:master"
    command: ["-redis-address", "redis:6379", "-web.listen-address", "0.0.0.0:9201"]
    depends_on:
      - redis
    networks:
      - app_net

  redis:
    image: "redislabs/redistimeseries:edge"
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app_net

  prometheus:
    image: "prom/prometheus:v2.41.0"
    command: ["--config.file=/prometheus.yml"]
    volumes:
      - ./prometheus.yaml:/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - app_net

volumes:
  app_todo-mysql-data:

networks:
  app_net:
    driver: overlay
