# version: '3'

# services:
#   app:
#     image: node:18-alpine
#     command: sh -c "sleep 20 && yarn install && yarn run dev"
#     ports:
#       - 80:3000
#     working_dir: /app
#     volumes:
#       - app_todo-app-data:/app
#     environment:
#       - MYSQL_HOST=mysql
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=secret
#       - MYSQL_DB=todos
#     depends_on:
#       - mysql
#     deploy:
#       replicas: 3
#       restart_policy:
#         condition: on-failure
#       update_config:
#         delay: 20s

#   mysql:
#     image: mysql:8.0
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_ROOT_PASSWORD=secret
#       - MYSQL_DATABASE=todos
#     deploy:
#       replicas: 1
#     volumes:
#       - app_todo-mysql-data:/var/lib/mysql

# volumes:
#   app_todo-app-data:
#     driver_opts:
#       type: nfs
#       o: addr=10.184.0.3,rw
#       device: ":/home/imprazz07/getting-started2/app"
#   app_todo-mysql-data:
  


version: '3'

services:
  app2:
    image: node:18-alpine
    command: sh -c "sleep 20 && yarn install && yarn run dev"
    ports:
      - 9002:9002
    working_dir: /app2
    volumes:
      - ./:/app2
    environment:
      - MYSQL_HOST=mysql2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=todos
    depends_on:
      - mysql2
    networks:
      - network2

  mysql2:
    image: mysql:8.0
    ports:
      - 8002:8002
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos
    volumes:
      - app_todo2-mysql-data:/var/lib/mysql
    networks:
      - network2

volumes:
  app_todo2-mysql-data:
networks:
  network2:
